/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visao;

import controle.ProprietarioControle;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import java.awt.image.RenderedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
//import static controle.ContatoController.validarCPF;
import visao.Dialog_TelaVeiculos;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.Proprietario;
import utilitarios.ManipularImagem;
import visao.TelaPrincipal;
import modelos.IProprietarioCRUD;

/**
 *
 * @author Luiz
 */
public class Dialog_TelaProprietarios extends javax.swing.JDialog {

    //Atributos
    IProprietarioCRUD contatoControle = null;
    DefaultTableModel model;
    Scanner nc = null;
    Proprietario contato = null;
    int indexContatoEmEdicao = -1;

    
    File imagemPessoal, imagemCnh;
    

    public Dialog_TelaProprietarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        contatoControle = new ProprietarioControle();
        model = (DefaultTableModel) jTableModeloProprietario.getModel();
        MostrarDados();
    }

    // Metodo para limpar tabela
    private void limparCampos() {
        jFormattedTextField_Cpf.setText("");
        jTextField1_Nome.setText("");
        jTextField_email.setText("");
        jFormattedTextField_Telefone.setText("");
        jFormattedTextFielCnh.setText("");
        jLabelFotoCNH.setIcon(null);
        jLabelFotoPessoal.setIcon(null);
        jComboBoxCategoria.setSelectedIndex(0);
    }
    private Proprietario criarContato() throws Exception {
        return new Proprietario(jFormattedTextField_Cpf.getText(), jTextField1_Nome.getText(), jTextField_email.getText(), jFormattedTextField_Telefone.getText(), jFormattedTextFielCnh.getText(), (String) jComboBoxCategoria.getSelectedItem(), jTextFieldImagemPessoal.getText(),jTextFieldCnh.getText() );

    }
    

    private void MostrarDados() {
        try {
            ArrayList<Proprietario> listaDeContatos = null;
            listaDeContatos = contatoControle.listagemDeContatos();
            DefaultTableModel model = (DefaultTableModel) jTableModeloProprietario.getModel();
            model.setNumRows(0);
            if (listaDeContatos.isEmpty()) {
                return;
            }
            for (int pos = 0; pos < listaDeContatos.size(); pos++) {
                Proprietario pessoa = listaDeContatos.get(pos);
                String[] linha = new String[8];
                linha[0] = pessoa.getCpf();
                linha[1] = pessoa.getNomeCompleto();
                linha[2] = pessoa.getEmail();
                linha[3] = pessoa.getTelefone();
                linha[4] = pessoa.getCnh();
                linha[5] = pessoa.getCategoria();
                linha[6] = pessoa.getImagemPessoal();
                linha[7] = pessoa.getImagemCnh();
                model.addRow(linha);
            }

            //System.out.println(listaDeContatos);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton2_BUSCAR = new javax.swing.JButton();
        jButton1_INCLUIR = new javax.swing.JButton();
        jButton4_ALTERAR = new javax.swing.JButton();
        jButton_LISTA = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableModeloProprietario = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jFormattedTextField_Cpf = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1_Nome = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jFormattedTextField_Telefone = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelFotoPessoal = new javax.swing.JLabel();
        jButtonFotoPessoal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelFotoCNH = new javax.swing.JLabel();
        jButtonFotoCnh = new javax.swing.JButton();
        jTextFieldCnh = new javax.swing.JTextField();
        jTextFieldImagemPessoal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextFielCnh = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("File");
        jMenuBar4.add(jMenu1);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(null);
        setIconImages(null);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(20, 20, 20));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2_BUSCAR.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2_BUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/m_buscar icon.png"))); // NOI18N
        jButton2_BUSCAR.setText("BUSCAR");
        jButton2_BUSCAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton2_BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_BUSCARActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2_BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 40));

        jButton1_INCLUIR.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1_INCLUIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/m_incluir icon.png"))); // NOI18N
        jButton1_INCLUIR.setText("INCLUIR");
        jButton1_INCLUIR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton1_INCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_INCLUIRActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1_INCLUIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 40));

        jButton4_ALTERAR.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4_ALTERAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/m_alterar icon.png"))); // NOI18N
        jButton4_ALTERAR.setText("ALTERAR");
        jButton4_ALTERAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton4_ALTERAR.setPreferredSize(new java.awt.Dimension(120, 39));
        jButton4_ALTERAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_ALTERARActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4_ALTERAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 160, 40));

        jButton_LISTA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_LISTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon_voltarP.png"))); // NOI18N
        jButton_LISTA.setText("VOLTAR");
        jButton_LISTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton_LISTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_LISTAMouseClicked(evt);
            }
        });
        jButton_LISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LISTAActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_LISTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 160, 40));

        jTableModeloProprietario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cpf", "Nome", "Email", "telefone", "Cnh", "Categoria", "Foto Pessoal", "Foto Cnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableModeloProprietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableModeloProprietarioMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableModeloProprietario);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 830, 110));

        jButton1.setBackground(new java.awt.Color(53, 53, 53));
        jButton1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/olho.png"))); // NOI18N
        jButton1.setText("Ocultar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 130, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1270, 150));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/whatsapp (1).png"))); // NOI18N
        jLabel32.setToolTipText("+55(62)99999-9999");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/instagram (1).png"))); // NOI18N
        jLabel33.setToolTipText("@forza");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sinal-do-twitter.png"))); // NOI18N
        jLabel34.setToolTipText("@forza");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jLabel35.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Desenvolvido por Forza ® Direitos Reservados.");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 271, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1270, 70));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/HOUVERPROPRIETARIO.png"))); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 90));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFormattedTextField_Cpf.setBackground(new java.awt.Color(102, 102, 102));
        jFormattedTextField_Cpf.setBorder(null);
        try {
            jFormattedTextField_Cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField_Cpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(jFormattedTextField_Cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 22, 220, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nome Completo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, 130, 15));

        jLabel3.setText("___________________________________");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 191, 220, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("CNH:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, 45, 15));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("CPF:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 45, 15));

        jLabel6.setText("_____________________________________");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 32, 240, -1));

        jLabel7.setText("___________________________________");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 137, 220, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Telefone:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 80, 15));

        jLabel9.setText("____________________________________");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 220, -1));

        jTextField1_Nome.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1_Nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1_Nome.setBorder(null);
        jPanel2.add(jTextField1_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 73, 220, 20));

        jTextField_email.setBackground(new java.awt.Color(102, 102, 102));
        jTextField_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_email.setBorder(null);
        jTextField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 127, 240, 20));

        jFormattedTextField_Telefone.setBackground(new java.awt.Color(102, 102, 102));
        jFormattedTextField_Telefone.setBorder(null);
        try {
            jFormattedTextField_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+55(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField_Telefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(jFormattedTextField_Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 181, 250, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon_info.png"))); // NOI18N
        jLabel11.setToolTipText("Digite uma CNH válida!");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon_info.png"))); // NOI18N
        jLabel12.setToolTipText("Digite um CPF válido!");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 32, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon_info.png"))); // NOI18N
        jLabel13.setToolTipText("Digite seu nome completo!");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 83, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon_info.png"))); // NOI18N
        jLabel14.setToolTipText("Digite um email válido!");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 137, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Email:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, 45, 15));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 308, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon_info.png"))); // NOI18N
        jLabel20.setToolTipText("Digite o número do seu telefone ou celular completo!");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 191, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon_info.png"))); // NOI18N
        jLabel16.setToolTipText("Adicionar Foto de preferencia PNG e 450x220!");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 20, 20));

        jComboBoxCategoria.setBackground(new java.awt.Color(53, 53, 53));
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "AB", "AC", "ACC", "AE", "B", "C", "D", "E" }));
        jComboBoxCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Categoria:"));
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 170, 40));

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFotoPessoal.setBackground(new java.awt.Color(51, 51, 51));
        jLabelFotoPessoal.setText("        ");
        jLabelFotoPessoal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabelFotoPessoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 220));

        jButtonFotoPessoal.setBackground(new java.awt.Color(51, 51, 51));
        jButtonFotoPessoal.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        jButtonFotoPessoal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon_galeria.png"))); // NOI18N
        jButtonFotoPessoal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButtonFotoPessoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoPessoalActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFotoPessoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 450, 40));

        jTabbedPane1.addTab("Pessoal", jPanel1);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFotoCNH.setText("        ");
        jLabelFotoCNH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabelFotoCNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 220));

        jButtonFotoCnh.setBackground(new java.awt.Color(51, 51, 51));
        jButtonFotoCnh.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        jButtonFotoCnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon_galeria.png"))); // NOI18N
        jButtonFotoCnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButtonFotoCnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoCnhActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFotoCnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 450, 40));

        jTabbedPane1.addTab("Cnh", jPanel3);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        jTextFieldCnh.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldCnh.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldCnh.setBorder(null);
        jTextFieldCnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCnhActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 310, 30));

        jTextFieldImagemPessoal.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldImagemPessoal.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldImagemPessoal.setBorder(null);
        jTextFieldImagemPessoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImagemPessoalActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldImagemPessoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 310, 20));

        jLabel18.setText("_________________________________");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 83, 210, -1));

        jFormattedTextFielCnh.setBackground(new java.awt.Color(102, 102, 102));
        jFormattedTextFielCnh.setBorder(null);
        try {
            jFormattedTextFielCnh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFielCnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFielCnhActionPerformed(evt);
            }
        });
        jPanel2.add(jFormattedTextFielCnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 210, 20));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lineBGatt.gif"))); // NOI18N
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -3, 800, 3));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 320));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));

        jMenu2.setBorder(null);
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menu.png"))); // NOI18N
        jMenu2.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        jMenu2.setHideActionText(true);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon_voltarP.png"))); // NOI18N
        jMenuItem3.setText("Menu Principal");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/olho.png"))); // NOI18N
        jMenuItem4.setText("FECHAR PROGRAMA");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaPrincipal Voltar = new TelaPrincipal();
        Voltar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1_INCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_INCLUIRActionPerformed
          try {
if (jTextField1_Nome.getText().isBlank() || jTextField_email.getText().isBlank() || jFormattedTextField_Telefone.getText().isBlank() || jFormattedTextField_Cpf.getText().isBlank() || jFormattedTextFielCnh.getText().isBlank() || jLabelFotoCNH.getIcon() == null || jLabelFotoPessoal.getIcon() == null) {
    JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos para incluir o proprietário!");


    } else {
        contatoControle.incluir(criarContato());
        MostrarDados();
        limparCamposIncluir();
        System.out.println(criarContato());
    }
} catch (Exception erro) {
    JOptionPane.showMessageDialog(this, erro.getMessage());
}


    
}

private void limparCamposIncluir() {
    // Código para limpar os campos de texto
    jTextField1_Nome.setText("");
    jFormattedTextField_Telefone.setText("");
    jTextField_email.setText("");
    jTextFieldImagemPessoal.setText("");
    jTextFieldCnh.setText("");
    jFormattedTextField_Telefone.setText("");
    jFormattedTextField_Cpf.setText("");
    jFormattedTextFielCnh.setText("");
    jFormattedTextField1.setText("");
    
    // ..

    }//GEN-LAST:event_jButton1_INCLUIRActionPerformed

    private void jButton4_ALTERARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_ALTERARActionPerformed
        //String cpf = jTableModeloProprietario.getModel().getValueAt(indexContatoEmEdicao, 0).toString();

        try {
            contatoControle.alterar(indexContatoEmEdicao, criarContato());
            System.out.println(criarContato());
            System.out.println(indexContatoEmEdicao);
            System.out.println(criarContato());
            limparCampos();
            MostrarDados();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton4_ALTERARActionPerformed

    private void jButton2_BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_BUSCARActionPerformed

        try {
            Proprietario buscaContato = contatoControle.buscar(jFormattedTextField_Cpf.getText());
            System.out.println(buscaContato);
            model.setNumRows(0); // limpando a tabela
            model.addRow(buscaContato.toString().split(";"));
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButton2_BUSCARActionPerformed

    private void jButton_LISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LISTAActionPerformed
        try {
         jFormattedTextField_Cpf.setEditable(true); 
         jTextFieldCnh.setText("");
         jTextFieldImagemPessoal.setText("");
            MostrarDados();
            limparCampos();
            System.out.println(contatoControle.listagemDeContatos());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButton_LISTAActionPerformed

    private void jTableModeloProprietarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableModeloProprietarioMouseClicked
        indexContatoEmEdicao = jTableModeloProprietario.getSelectedRow();
        
        Object[] dadosContato = {
            model.getValueAt(indexContatoEmEdicao, 0),
            model.getValueAt(indexContatoEmEdicao, 1),
            model.getValueAt(indexContatoEmEdicao, 2),
            model.getValueAt(indexContatoEmEdicao, 3),
            model.getValueAt(indexContatoEmEdicao, 4),
            model.getValueAt(indexContatoEmEdicao, 5),
            model.getValueAt(indexContatoEmEdicao, 6),
            model.getValueAt(indexContatoEmEdicao, 7)};
        jFormattedTextField_Cpf.setEditable(false); 
        jFormattedTextField_Cpf.setText("" + dadosContato[0]);
         
        jTextField1_Nome.setText("" + dadosContato[1]);
        jTextField_email.setText("" + dadosContato[2]);
        jFormattedTextField_Telefone.setText("" + dadosContato[3]);
        jFormattedTextFielCnh.setText("" + dadosContato[4]);
        jComboBoxCategoria.setSelectedItem("" + dadosContato[5]);
   

        jTextFieldImagemPessoal.setText("" + dadosContato[6]);
        ImageIcon imagemPerfil = new ImageIcon("" + dadosContato[6]);
        jLabelFotoPessoal.setIcon(new ImageIcon(imagemPerfil.getImage().getScaledInstance(jLabelFotoPessoal.getWidth(), jLabelFotoPessoal.getHeight(), Image.SCALE_DEFAULT)));
        
        jTextFieldCnh.setText("" + dadosContato[7]);
        ImageIcon imagemCarteira = new ImageIcon("" + dadosContato[7]);
         jLabelFotoCNH.setIcon(new ImageIcon(imagemCarteira.getImage().getScaledInstance(jLabelFotoCNH.getWidth(), jLabelFotoCNH.getHeight(), Image.SCALE_DEFAULT)));

             

    }//GEN-LAST:event_jTableModeloProprietarioMouseClicked

    private void jButton_LISTAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LISTAMouseClicked
        //limparCampos();
    }//GEN-LAST:event_jButton_LISTAMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
System.exit(0);       
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jTextFieldImagemPessoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImagemPessoalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImagemPessoalActionPerformed

    private void jTextFieldCnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCnhActionPerformed

    private void jFormattedTextFielCnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFielCnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFielCnhActionPerformed

    private void jButtonFotoCnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoCnhActionPerformed
  JFileChooser arquivo = new JFileChooser();
arquivo.setDialogTitle("Selecione uma Imagem");
arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
int op = arquivo.showOpenDialog(this);
if (op == JFileChooser.APPROVE_OPTION) {
    File file = arquivo.getSelectedFile();

    // Check if the selected file is larger than 10 MB
    long fileSizeInBytes = file.length();
    long fileSizeInMB = fileSizeInBytes / (1024 * 1024);

    if (fileSizeInMB > 10) {
        JOptionPane.showMessageDialog(this, "O tamanho da imagem selecionada é maior do que 10 MB.", "Erro", JOptionPane.ERROR_MESSAGE);
    } else {
        imagemCnh = file;
        String imagemHabilitacao = file.getAbsolutePath();
        jTextFieldCnh.setText(imagemHabilitacao);

        ImageIcon imagemCarteira = new ImageIcon(imagemCnh.getAbsolutePath());

        jLabelFotoCNH.setIcon(new ImageIcon(imagemCarteira.getImage().getScaledInstance(jLabelFotoCNH.getWidth(), jLabelFotoCNH.getHeight(), Image.SCALE_DEFAULT)));
    }
}





    }//GEN-LAST:event_jButtonFotoCnhActionPerformed

    private void jButtonFotoPessoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoPessoalActionPerformed
    JFileChooser arquivo = new JFileChooser();
    arquivo.setDialogTitle("Selecione uma Imagem");
    arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int op = arquivo.showOpenDialog(this);
    if (op == JFileChooser.APPROVE_OPTION) {
        File file = arquivo.getSelectedFile();

        // Check if the selected file is larger than 10 MB
        long fileSizeInBytes = file.length();
        long fileSizeInMB = fileSizeInBytes / (1024 * 1024);

        if (fileSizeInMB > 10) {
            JOptionPane.showMessageDialog(this, "O tamanho da imagem selecionada é maior do que 10 MB.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            imagemPessoal = file;
            String imagemHabilitacao = file.getAbsolutePath();
            jTextFieldImagemPessoal.setText(imagemHabilitacao);

            ImageIcon imagemCarteira = new ImageIcon(imagemPessoal.getAbsolutePath());

            // Redimensionar a imagem para se ajustar à JLabel
            Image imagemRedimensionada = imagemCarteira.getImage().getScaledInstance(450, 220, Image.SCALE_DEFAULT);
            ImageIcon imagemRedimensionadaIcon = new ImageIcon(imagemRedimensionada);

            jLabelFotoPessoal.setIcon(imagemRedimensionadaIcon);
        }
    }
    }//GEN-LAST:event_jButtonFotoPessoalActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jTextField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          if (jTableModeloProprietario.isVisible()) {
        // Se a tabela está visível, ocultá-la
        jTableModeloProprietario.setVisible(false);
        jButton1.setText("Visualizar");  // Altera o texto do botão para "Mostrar"
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/olho (1).png")));
    } else {
        // Se a tabela está oculta, mostrá-la novamente
        jTableModeloProprietario.setVisible(true);
        jButton1.setText("Ocultar");  // Altera o texto do botão para "Ocultar"
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/olho.png")));

        // Limpar o modelo da tabela antes de adicionar os novos dados
        model.setRowCount(0);

        // Chamar o método para preencher o modelo da tabela com os dados
        MostrarDados();}
          
          
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog_TelaProprietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog_TelaProprietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog_TelaProprietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog_TelaProprietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog_TelaProprietarios dialog = new Dialog_TelaProprietarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_INCLUIR;
    private javax.swing.JButton jButton2_BUSCAR;
    private javax.swing.JButton jButton4_ALTERAR;
    private javax.swing.JButton jButtonFotoCnh;
    private javax.swing.JButton jButtonFotoPessoal;
    private javax.swing.JButton jButton_LISTA;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JFormattedTextField jFormattedTextFielCnh;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField_Cpf;
    private javax.swing.JFormattedTextField jFormattedTextField_Telefone;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFotoCNH;
    private javax.swing.JLabel jLabelFotoPessoal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableModeloProprietario;
    private javax.swing.JTextField jTextField1_Nome;
    private javax.swing.JTextField jTextFieldCnh;
    private javax.swing.JTextField jTextFieldImagemPessoal;
    private javax.swing.JTextField jTextField_email;
    // End of variables declaration//GEN-END:variables

}
